{
 "title": "Rocket Pool - ODAO Member Dashboard",
 "description": "ODAO member dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# YOUR NODE" } },
  {
   "title": "Balances Performance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_trusted_node_balances_performance{}"
    }
   ]
  },
  {
   "title": "Prices Performance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_trusted_node_prices_performance{}"
    }
   ]
  },
  {
   "title": "ETH Balance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_balance{Token=\"ETH\"}"
    }
   ]
  },
  {
   "title": "Proposals Requiring Vote",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_trusted_node_unvoted_proposal_count"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 } },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 }, "options": { "content": "# PROPOSALS" } },
  {
   "title": "Active Proposal Votes",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rocketpool_trusted_node_proposal_table{category=\"for\"}"
    },
    {
     "expr": "rocketpool_trusted_node_proposal_table{category=\"against\"}"
    },
    {
     "expr": "ceil(rocketpool_trusted_node_proposal_table{category=\"required\"})"
    }
   ]
  },
  {
   "title": "Proposals",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_trusted_node_proposal_count{}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 } },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 29 }, "options": { "content": "# PARTICIPATION" } },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 32 }, "options": { "content": "## BALANCES" } },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 12, "y": 32 }, "options": { "content": "## PRICES" } },
  {
   "title": "Balances Participation Probability",
   "type": "gauge",
   "description": "This is the probability that the recent balances participation from oDAO members is fairly distributed.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_odao_balances_probability{}*100"
    }
   ]
  },
  {
   "title": "Balances In Consensus",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocketpool_odao_balances_participation{}) - count(rocketpool_odao_balances_participation{}) * 0.51 > 0"
    }
   ]
  },
  {
   "title": "Prices Participation Probability",
   "type": "gauge",
   "description": "This is the probability that the recent prices participation from oDAO members is fairly distributed.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_odao_prices_probability{}*100"
    }
   ]
  },
  {
   "title": "Prices In Consensus",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocketpool_odao_prices_participation{}) - count(rocketpool_odao_prices_participation{}) * 0.51 > 0"
    }
   ]
  },
  {
   "title": "Balances Participation",
   "type": "status-history",
   "description": "This shows which members participated in the most recent balances update.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rocketpool_odao_balances_participation{}) - count(rocketpool_odao_balances_participation{}) * 0.51 + 1",
     "legendFormat": "[consensus]"
    },
    {
     "expr": "rocketpool_odao_balances_participation{}",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Prices Participation",
   "type": "status-history",
   "description": "This shows which members participated in the most recent prices update.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(rocketpool_odao_prices_participation{}) - count(rocketpool_odao_prices_participation{}) * 0.51 + 1",
     "legendFormat": "[consensus]"
    },
    {
     "expr": "rocketpool_odao_prices_participation{}",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Balances Relative Performance",
   "type": "timeseries",
   "description": "Shows relative recent balances submission performance between members and their peers.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(rocketpool_odao_balances_recent_participation{}[1h])",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Prices Relative Performance",
   "type": "timeseries",
   "description": "Shows relative recent prices submission performance between members and their peers.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(rocketpool_odao_balances_recent_participation{}[1h])",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_odao_current_eth1_block{}"
    }
   ]
  },
  {
   "title": "Network Balance Blocks (behind)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rocketpool_odao_current_eth1_block{} - rocketpool_odao_latest_reportable_block{})"
    }
   ]
  },
  {
   "title": "Network Prices Blocks (behind)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rocketpool_odao_current_eth1_block{} - rocketpool_odao_prices_block{})"
    }
   ]
  },
  {
   "title": "Effective RPL Stake Blocks (behind)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rocketpool_odao_current_eth1_block{} - rocketpool_odao_effective_rpl_stake_block{})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 71 } },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 73 }, "options": { "content": "# BALANCES" } },
  {
   "title": "Member ETH Balance",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "expr": "rocketpool_trusted_node_eth_balance{}",
     "legendFormat": "{{member}}"
    }
   ]
  }
 ]
}