const { chromium } = require('playwright-extra');
const fs = require('fs');
const path = require('path');

const inputMdPath = process.argv[2];
const outputPdfPath = process.argv[3] || inputMdPath.replace('.md', '.pdf');

if (!inputMdPath || !fs.existsSync(inputMdPath)) {
    console.error('Usage: node scripts/mdToPdf.js <input_path.md> [output_path.pdf]');
    process.exit(1);
}

async function convert() {
    console.log(`🚀 Tuppli PDF Engine: Converting ${path.basename(inputMdPath)}...`);
    const text = fs.readFileSync(inputMdPath, 'utf-8');

    const htmlTemplate = `
      <!DOCTYPE html>
      <html>
      <head>
          <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
          <style>
              @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap');
              body { 
                font-family: 'Inter', sans-serif; 
                line-height: 1.6; 
                color: #0F172A; 
                margin: 0;
                padding: 40px;
                background: #fff;
              }
              .report-container { max-width: 800px; margin: 0 auto; }
              h1 { font-weight: 800; color: #0F172A; font-size: 32px; border-bottom: 4px solid #95E9EC; padding-bottom: 10px; margin-bottom: 30px; }
              h2 { font-weight: 800; color: #1E293B; font-size: 22px; margin-top: 40px; }
              h3 { font-weight: 600; color: #475569; font-size: 18px; }
              p { color: #334155; margin-bottom: 20px; }
              strong { color: #0F172A; font-weight: 800; }
              .severity-high { color: #EF4444; font-weight: 800; }
              .severity-medium { color: #F59E0B; font-weight: 800; }
              .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #E2E8F0; font-size: 12px; color: #94A3B8; text-align: center; }
              .logo { font-weight: 800; color: #0F172A; font-size: 20px; margin-bottom: 40px; }
              .pill { background: #F1F5F9; border-radius: 99px; padding: 4px 12px; font-size: 12px; font-weight: 600; color: #475569; }
          </style>
      </head>
      <body>
          <div class="report-container">
              <div class="logo">🛡️ TUPPLI</div>
              <div id="content"></div>
              <div class="footer">
                  Generated by Tuppli AI Forensic Engine. Confidential Creator Security Audit. © ${new Date().getFullYear()} Tuppli.
              </div>
          </div>
          <script>
            document.getElementById('content').innerHTML = marked.parse(\`${text.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`);
          </script>
      </body>
      </html>
    `;

    const tmpHtml = path.join('/tmp', `report_${Date.now()}.html`);
    fs.writeFileSync(tmpHtml, htmlTemplate);

    const browser = await chromium.launch({ headless: true });
    const page = await browser.newPage();
    await page.goto(`file://${tmpHtml}`, { waitUntil: 'networkidle' });

    await page.pdf({
        path: outputPdfPath,
        format: 'A4',
        printBackground: true,
        margin: { top: '0px', bottom: '0px', left: '0px', right: '0px' }
    });

    await browser.close();
    fs.unlinkSync(tmpHtml);
    console.log(`✅ Report finalized: ${outputPdfPath}`);
}

convert().catch(console.error);
